#!/usr/bin/python

from os import stat, listdir
#from pwd import getpwuid
#import sys
import subprocess

from pwd import getpwuid
from grp import getgrgid

def get_owner_group(filename):
    return getpwuid(stat(filename).st_uid).pw_name+":"+getgrgid(stat(filename).st_gid).gr_name

print "Please, choose:"
print "---------------"
print "1: set files and directories owner"
print "2: set files permissions to 644"
print "3: set directories permissions to 755"
print "4: do all"

user_input = raw_input("> ")

if user_input is "1" or user_input is "4":
    perm = []
    for fd in listdir("."):
        o = get_owner_group(fd)
        if o not in perm:
            perm.append(o)
    print perm
    i = int(raw_input("permissions: ")) - 1
    if i < len(perm):
        subprocess.call("chown -R "+perm[i]+" *", shell=True)
    else:
        print "Bad choose"
if user_input is "2" or user_input is "4":
    subprocess.call("find . -type f -exec chmod 644 {}\;", shell=True)
if user_input is "3" or user_input is "4":
    subprocess.call("find . -type d -exec chmod 755 {}\;", shell=True)

print "Exit"
