#!/bin/bash
### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tomcat service
# Description:       Script che consente di avviare tomcat come servizio
### END INIT INFO

# Author: Michele Milidoni <mmilidoni@zenitlab.it>

export JAVA_HOME=/opt/jdk 
#set JAVA_OPTS=%JAVA_OPTS% -Duser.language=it -Duser.region=IT
#set JAVA_OPTS=%JAVA_OPTS% -Duser.language=it -Duser.region=IT
#export JAVA_OPTS

export JAVA_OPTS=' -Duser.language=it -Duser.region=IT'
TOMCATPATH=/opt/tomcat/bin

if [ -r /etc/default/locale ]; then
        . /etc/default/locale
        export LANG
fi

case "$1" in
start)
cd $TOMCATPATH
./startup.sh  -Duser.language=it -Duser.region=IT
;;
stop)
cd $TOMCATPATH
./shutdown.sh
;;
restart)
cd $TOMCATPATH
./shutdown.sh
sleep 3
cd $TOMCATPATH
./startup.sh -Duser.language=it -Duser.region=IT
;;
*)
echo $"usage: $0 {start|stop|restart}"
exit 1
esac
