#!/bin/bash
#-------------------
#|    ZENIT SRL    |
#| www.zenitlab.it |
#-------------------
# Script che consente di avviare tomcat come servizio.
# Generalmente viene caricato nella directory /etc/init.d/
# ed inserito nei runlevel

### BEGIN INIT INFO
# Provides:      tomcat
# Required-Start:   $network $remote_fs $syslog
# Required-Stop:
# Default-Start:   S
# Default-Stop:
# Short-Description:   Activate tomcat.
### END INIT INFO

export JAVA_HOME=/usr/java/jdk1.6.0_25/ 
#set JAVA_OPTS=%JAVA_OPTS% -Duser.language=it -Duser.region=IT
#set JAVA_OPTS=%JAVA_OPTS% -Duser.language=it -Duser.region=IT
#export JAVA_OPTS

export JAVA_OPTS=' -Duser.language=it -Duser.region=IT'
TOMCATPATH=/opt/tomcat/bin

if [ -r /etc/default/locale ]; then
        . /etc/default/locale
        export LANG
fi

case "$1" in
start)
cd /opt/tomcat/bin
./startup.sh  -Duser.language=it -Duser.region=IT
;;
stop)
cd /opt/tomcat/bin
./shutdown.sh
;;
restart)
cd /opt/tomcat/bin
./shutdown.sh
sleep 3
cd /opt/tomcat/bin
./startup.sh -Duser.language=it -Duser.region=IT
;;
*)
echo $"usage: $0 {start|stop|restart}"
exit 1
esac
